# Generated by Django 3.2.19 on 2023-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_usermed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
