# Generated by Django 3.2.19 on 2023-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_usermed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermed',
            name='secretword',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
